CREATE TABLE [dbo].[File]
(
	[FileID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [UserID] INT NULL, 
    [Data] NVARCHAR(MAX) NOT NULL, 
    [Preview] NVARCHAR(MAX) NOT NULL, 
    CONSTRAINT [FK_File_User] FOREIGN KEY ([UserID]) REFERENCES [User]([UserID])
)
